"""Add booking destination, vehicle features policy, owner rating

Revision ID: 2a4d48ae0e14
Revises: b5df744da3cc
Create Date: 2025-10-22 19:22:49.105019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4d48ae0e14'
down_revision = 'b5df744da3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_rating', sa.Float(), nullable=True))

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_policy', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('cancellation_policy')
        batch_op.drop_column('features')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('owner_rating')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('destination')

    # ### end Alembic commands ###
