"""Add created_at, bio, and verification status to user

Revision ID: 2b3fec8595ec
Revises: 2a4d48ae0e14
Create Date: 2025-10-26 18:25:03.394866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3fec8595ec'
down_revision = '2a4d48ae0e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('identity_verified', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_policy', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('cancellation_policy')
        batch_op.drop_column('features')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('identity_verified')
        batch_op.drop_column('phone_verified')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('bio')
        batch_op.drop_column('created_at')
        batch_op.drop_column('owner_rating')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('destination')

    # ### end Alembic commands ###
