"""Add last_password_change to user table

Revision ID: 2bf0d35a9b02
Revises: 2b3fec8595ec
Create Date: 2025-10-29 11:52:54.424557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf0d35a9b02'
down_revision = '2b3fec8595ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_password_change', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_password_change')

    # ### end Alembic commands ###
