"""Add OwnerSettings model

Revision ID: 904f88f1fa81
Revises: 8eb8a9c1b38a
Create Date: 2025-10-03 23:53:28.841650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904f88f1fa81'
down_revision = '8eb8a9c1b38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('booking_confirmations', sa.Boolean(), nullable=True),
    sa.Column('payment_notifications', sa.Boolean(), nullable=True),
    sa.Column('maintenance_reminders', sa.Boolean(), nullable=True),
    sa.Column('marketing_emails', sa.Boolean(), nullable=True),
    sa.Column('weekly_reports', sa.Boolean(), nullable=True),
    sa.Column('monthly_statements', sa.Boolean(), nullable=True),
    sa.Column('security_alerts', sa.Boolean(), nullable=True),
    sa.Column('default_payment_method', sa.String(length=50), nullable=True),
    sa.Column('auto_payouts', sa.Boolean(), nullable=True),
    sa.Column('payout_threshold', sa.Integer(), nullable=True),
    sa.Column('payout_frequency', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('auto_accept_bookings', sa.Boolean(), nullable=True),
    sa.Column('minimum_booking_duration', sa.Integer(), nullable=True),
    sa.Column('maximum_booking_duration', sa.Integer(), nullable=True),
    sa.Column('buffer_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_settings')
    # ### end Alembic commands ###
